name = "EcmwfRequests"
uuid = "c0c4b1a4-92fd-414d-990e-850c1287bada"
authors = ["tcarion <tristan.carion@gmail.com> and contributors"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
